using Microsoft.Extensions.Logging;

namespace Avvo.Core.Logging
{
    /// <summary>
    /// This class is used to define the JSON representation of a log entry.
    /// </summary>
    public class LogEntry
    {
        /// <summary>
        /// This is the name/categry of the log entry.
        /// </summary>
        public string LogName { get; set; }

        /// <summary>
        /// This is the level of the log entry.
        /// </summary>
        public LogLevel LogLevel { get; set; }

        /// <summary>
        /// This is the message content of the log entry.
        /// </summary>
        public object Message { get; set; }

        /// <summary>
        /// This is the correlation data related to this log entry.
        /// </summary>
        public CorrelationData Correlation { get; set; }

        /// <summary>
        /// This is the exception related to this log entry.
        /// </summary>
        public Exception Exception { get; set; }

        /// <summary>
        /// This is the event id related to this log entry.
        /// </summary>
        public int EventId { get; set; }

        /// <summary>
        /// This is the details of the application this log was generated by
        /// </summary>
        public IApplicationDetails Application { get; set; }

        /// <summary>
        /// This is the datetime the log entry ocurred
        /// </summary>
        public DateTime Timestamp { get; set; }
    }
}
